using System.IO.Compression;
using System.Text;
using StackOverGrave.Api.Models;

namespace StackOverGrave.Api.Services;

public class PackagingService : IPackagingService
{
    private readonly ILogger<PackagingService> _logger;

    public PackagingService(ILogger<PackagingService> logger)
    {
        _logger = logger;
    }

    public Task<byte[]> GenerateZipAsync(ConversionResult result)
    {
        using var memoryStream = new MemoryStream();
        using (var archive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
        {
            var tech = result.Project?.Technology ?? TechnologyType.Unknown;
            
            // Add converted code file
            var codeFileName = GetCodeFileName(result.Project?.OriginalFilename ?? "converted", tech);
            AddFileToZip(archive, $"src/{codeFileName}", result.ConvertedCode);

            // Add README
            var readme = GenerateReadme(result);
            AddFileToZip(archive, "README.md", readme);

            // Add MIGRATION_NOTES
            var migrationNotes = GenerateMigrationNotes(result);
            AddFileToZip(archive, "MIGRATION_NOTES.md", migrationNotes);

            // Add project file based on technology
            var projectFile = GenerateProjectFile(result);
            if (!string.IsNullOrEmpty(projectFile.content))
            {
                AddFileToZip(archive, projectFile.filename, projectFile.content);
            }
        }

        memoryStream.Position = 0;
        return Task.FromResult(memoryStream.ToArray());
    }

    private void AddFileToZip(ZipArchive archive, string entryName, string content)
    {
        var entry = archive.CreateEntry(entryName);
        using var entryStream = entry.Open();
        using var writer = new StreamWriter(entryStream, Encoding.UTF8);
        writer.Write(content);
    }

    private string GetCodeFileName(string originalName, TechnologyType tech)
    {
        var baseName = Path.GetFileNameWithoutExtension(originalName);
        return tech switch
        {
            TechnologyType.VB6 => $"{baseName}.cs",
            TechnologyType.ActionScript => $"{baseName}.component.ts",
            TechnologyType.Silverlight => $"{baseName}.component.ts",
            TechnologyType.DotNetFramework => $"{baseName}.cs",
            _ => $"{baseName}.txt"
        };
    }

    private string GenerateReadme(ConversionResult result)
    {
        var tech = result.Project?.Technology ?? TechnologyType.Unknown;
        var targetTech = GetTargetTech(tech);
        var originalName = result.Project?.OriginalFilename ?? "Unknown";

        var sb = new StringBuilder();
        sb.AppendLine($"# Converted Project: {Path.GetFileNameWithoutExtension(originalName)}");
        sb.AppendLine();
        sb.AppendLine("## Original Technology");
        sb.AppendLine($"{tech}");
        sb.AppendLine();
        sb.AppendLine("## New Technology");
        sb.AppendLine($"{targetTech}");
        sb.AppendLine();
        sb.AppendLine("## Quick Start");
        sb.AppendLine();
        sb.AppendLine(GetQuickStartInstructions(tech));
        sb.AppendLine();
        sb.AppendLine("## Files Included");
        sb.AppendLine();
        sb.AppendLine("- `src/` - Converted source code");
        sb.AppendLine("- `README.md` - This file");
        sb.AppendLine("- `MIGRATION_NOTES.md` - Detailed migration information");
        sb.AppendLine();
        sb.AppendLine("## Next Steps");
        sb.AppendLine();
        sb.AppendLine("1. Review the converted code");
        sb.AppendLine("2. Install dependencies (see MIGRATION_NOTES.md)");
        sb.AppendLine("3. Address breaking changes");
        sb.AppendLine("4. Test thoroughly");
        sb.AppendLine("5. Deploy!");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine("*Generated by StackOverGrave - Where Legacy Code Rests in Peace*");

        return sb.ToString();
    }

    private string GenerateMigrationNotes(ConversionResult result)
    {
        var migrationData = System.Text.Json.JsonSerializer.Deserialize<MigrationData>(result.MigrationNotes);
        
        var sb = new StringBuilder();
        sb.AppendLine("# Migration Notes");
        sb.AppendLine();
        sb.AppendLine($"**Processed:** {result.ProcessedAt:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        if (migrationData?.MigrationNotes?.Any() == true)
        {
            sb.AppendLine("## Changes Made");
            sb.AppendLine();
            foreach (var note in migrationData.MigrationNotes)
            {
                sb.AppendLine($"- {note}");
            }
            sb.AppendLine();
        }

        if (migrationData?.Dependencies?.Any() == true)
        {
            sb.AppendLine("## Dependencies Required");
            sb.AppendLine();
            foreach (var dep in migrationData.Dependencies)
            {
                sb.AppendLine($"- `{dep}`");
            }
            sb.AppendLine();
            sb.AppendLine("Install with:");
            sb.AppendLine("```bash");
            sb.AppendLine(GetInstallCommand(result.Project?.Technology ?? TechnologyType.Unknown, migrationData.Dependencies));
            sb.AppendLine("```");
            sb.AppendLine();
        }

        if (migrationData?.BreakingChanges?.Any() == true)
        {
            sb.AppendLine("## ⚠️ Breaking Changes");
            sb.AppendLine();
            foreach (var change in migrationData.BreakingChanges)
            {
                sb.AppendLine($"- {change}");
            }
            sb.AppendLine();
        }

        if (migrationData?.Warnings?.Any() == true)
        {
            sb.AppendLine("## 🚨 Warnings");
            sb.AppendLine();
            foreach (var warning in migrationData.Warnings)
            {
                sb.AppendLine($"- {warning}");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private (string filename, string content) GenerateProjectFile(ConversionResult result)
    {
        var tech = result.Project?.Technology ?? TechnologyType.Unknown;
        
        return tech switch
        {
            TechnologyType.VB6 or TechnologyType.DotNetFramework => GenerateCsProjFile(result),
            TechnologyType.ActionScript or TechnologyType.Silverlight => GeneratePackageJson(result),
            _ => ("", "")
        };
    }

    private (string filename, string content) GenerateCsProjFile(ConversionResult result)
    {
        var projectName = Path.GetFileNameWithoutExtension(result.Project?.OriginalFilename ?? "ConvertedProject");
        
        var content = $@"<Project Sdk=""Microsoft.NET.Sdk"">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include=""Microsoft.Extensions.Logging"" Version=""8.0.0"" />
    <PackageReference Include=""Microsoft.Extensions.DependencyInjection"" Version=""8.0.0"" />
  </ItemGroup>

</Project>";

        return ($"{projectName}.csproj", content);
    }

    private (string filename, string content) GeneratePackageJson(ConversionResult result)
    {
        var projectName = Path.GetFileNameWithoutExtension(result.Project?.OriginalFilename ?? "converted-project");
        
        var content = $@"{{
  ""name"": ""{projectName.ToLower()}"",
  ""version"": ""1.0.0"",
  ""scripts"": {{
    ""start"": ""ng serve"",
    ""build"": ""ng build"",
    ""test"": ""ng test""
  }},
  ""dependencies"": {{
    ""@angular/core"": ""^17.0.0"",
    ""@angular/common"": ""^17.0.0"",
    ""@angular/material"": ""^17.0.0"",
    ""rxjs"": ""^7.8.0""
  }}
}}";

        return ("package.json", content);
    }

    private string GetTargetTech(TechnologyType tech) => tech switch
    {
        TechnologyType.VB6 => "C# .NET 8",
        TechnologyType.ActionScript => "TypeScript/Angular",
        TechnologyType.Silverlight => "Angular Material",
        TechnologyType.DotNetFramework => ".NET 8",
        _ => "Modern Framework"
    };

    private string GetQuickStartInstructions(TechnologyType tech) => tech switch
    {
        TechnologyType.VB6 or TechnologyType.DotNetFramework => @"```bash
dotnet restore
dotnet build
dotnet run
```",
        TechnologyType.ActionScript or TechnologyType.Silverlight => @"```bash
npm install
npm start
```",
        _ => "See documentation for setup instructions."
    };

    private string GetInstallCommand(TechnologyType tech, List<string> dependencies)
    {
        return tech switch
        {
            TechnologyType.VB6 or TechnologyType.DotNetFramework => 
                string.Join("\n", dependencies.Select(d => $"dotnet add package {d}")),
            TechnologyType.ActionScript or TechnologyType.Silverlight => 
                $"npm install {string.Join(" ", dependencies)}",
            _ => "# Install dependencies manually"
        };
    }
}

public interface IPackagingService
{
    Task<byte[]> GenerateZipAsync(ConversionResult result);
}
